#!/bin/bash

credmark-dev list
echo ""
echo "Compound Historical"
echo ""
credmark-dev run compound-v2.all-pools-values-historical-plan --input '{}' -l token.price,token.price-ext,uniswap-v2.get-average-price,uniswap-v3.get-average-price,sushiswap.get-average-price,compound-v2.get-comptroller,compound-v2.get-pool-info,finance.get-one,compound-v2.all-pools-info,compound-v2.all-pools-values,compound-v2.pool-value,compound-v2.get-pools -b 14234904 --format_json
echo ""
echo "Run Price Examples"
echo ""
credmark-dev run token.price-ext --input '{"symbol": "AAVE"}' -b 14234904 --format_json
credmark-dev run token.price-ext --input '{"address": "0x7fc66500c84a76ad7e9c93437bfc5ac33e2ddae9"}' -b 14234904 --format_json
echo ""
echo "Run Finance Examples"
echo ""
credmark-dev run finance.var-regtest --input '{}' -l finance.var-engine,finance.var-reference,token.price-ext,finance.get-one,uniswap-v2.get-average-price,uniswap-v3.get-average-price,sushiswap.get-average-price -b 14234904 --format_json
credmark-dev run finance.var-engine --input '{"portfolio": {"positions": [{"amount": -0.5, "asset": {"symbol": "WETH"}}, {"amount": 0.5, "asset": {"symbol": "WETH"}}]}, "window": "30 days","intervals": ["1 day"], "confidences": [0.05], "dev_mode":true, "verbose":true}' -l finance.var-engine,finance.var-reference,token.price-ext,finance.get-one,uniswap-v2.get-average-price,uniswap-v3.get-average-price,sushiswap.get-average-price -b 14234904 --format_json
credmark-dev run finance.var-engine --input '{"portfolio": {"positions": [{"amount":  0.5, "asset": {"symbol": "WETH"}}, {"amount": 0.5, "asset": {"symbol": "WETH"}}]}, "window": "30 days","intervals": ["1 day"], "confidences": [0.05], "dev_mode":true, "verbose":true}' -l finance.var-engine,finance.var-reference,token.price-ext,finance.get-one,uniswap-v2.get-average-price,uniswap-v3.get-average-price,sushiswap.get-average-price -b 14234904 --format_json
credmark-dev run finance.var-engine --input '{"portfolio": {"positions": [{"amount":  1, "asset": {"symbol": "WETH"}}]}, "window": "30 days", "intervals": ["1 day"], "confidences": [0.05], "dev_mode":true, "verbose":true}' -l finance.var-engine,finance.var-reference,token.price-ext,finance.get-one,uniswap-v2.get-average-price,uniswap-v3.get-average-price,sushiswap.get-average-price -b 14234904 --format_json
credmark-dev run finance.var-engine --input '{"portfolio": {"positions": [{"amount": -1, "asset": {"symbol": "WETH"}}]}, "window": "30 days", "intervals": ["1 day"], "confidences": [0.05], "dev_mode":true, "verbose":true}' -l finance.var-engine,finance.var-reference,token.price-ext,finance.get-one,uniswap-v2.get-average-price,uniswap-v3.get-average-price,sushiswap.get-average-price -b 14234904 --format_json
credmark-dev run finance.var-engine --input '{"portfolio": {"positions": [{"amount":  1, "asset": {"symbol": "WETH"}}]}, "window": "90 days", "intervals": ["1 day","10 days"], "confidences": [0.01,0.05], "dev_mode":true, "verbose":true}' -l finance.var-engine,finance.var-reference,token.price-ext,finance.get-one,uniswap-v2.get-average-price,uniswap-v3.get-average-price,sushiswap.get-average-price -b 14234904 --format_json
credmark-dev run finance.lcr --input '{"address": "0xe78388b4ce79068e89bf8aa7f218ef6b9ab0e9d0", "cashflow_shock": 1e10}' -b 14234904 --format_json
credmark-dev run finance.var-engine --input '{"portfolio": {"positions": [{"amount":  1, "asset": {"symbol": "WETH"}}]}, "window": "600 days", "intervals": ["1 day", "2 day", "5 day", "10 day","12 days"], "as_ofs": ["2022-02-17", "2022-02-05"], "as_of_is_range":true, "confidences": [0, 0.01, 0.05,1.0], "dev_mode":true, "verbose":true}' -l finance.var-engine,finance.var-reference,token.price-ext,finance.get-one,uniswap-v2.get-average-price,uniswap-v3.get-average-price,sushiswap.get-average-price -b 14234904 --format_json
credmark-dev run finance.var-engine --input '{"portfolio": {"positions": [{"amount":  1, "asset": {"symbol": "CMK"}}]}, "window": "600 days", "intervals": ["1 day"], "as_ofs": ["2022-02-17"], "confidences": [0.01], "dev_mode":true, "verbose":true}' -l finance.var-engine,finance.var-reference,token.price-ext,finance.get-one,uniswap-v2.get-average-price,uniswap-v3.get-average-price,sushiswap.get-average-price -b 14234904 --format_json
echo ""
echo "Run Aave VaR Examples"
echo ""
credmark-dev run finance.var-aave --input '{"window": "30 days", "intervals": ["10 day"], "confidences": [0.01], "dev_mode":false, "verbose":true}' -l aave.token-asset,aave.lending-pool-assets,finance.var-engine,finance.var-reference,token.price-ext,finance.get-one,uniswap-v2.get-average-price,uniswap-v3.get-average-price,sushiswap.get-average-price -b 14234904 --format_json
credmark-dev run finance.var-aave --input '{"window": "30 days", "intervals": ["10 day"], "as_ofs": ["2022-02-10", "2022-02-15"], "as_of_is_range":true, "confidences": [0.01], "dev_mode":false, "verbose":true}' -l aave.token-asset,aave.lending-pool-assets,finance.var-engine,finance.var-reference,token.price-ext,finance.get-one,uniswap-v2.get-average-price,uniswap-v3.get-average-price,sushiswap.get-average-price -b 14234904 --format_json
credmark-dev run finance.var-aave --input '{"window": "1 days", "intervals": ["10 day"], "as_ofs": ["2020-11-30", "2022-02-18"], "as_of_is_range":true, "confidences": [0.01], "dev_mode":true, "verbose":true, "aave_history":true}' -l aave.token-asset,aave.lending-pool-assets,finance.var-engine,finance.var-reference,token.price-ext,finance.get-one,uniswap-v2.get-average-price,uniswap-v3.get-average-price,sushiswap.get-average-price -b 14234904 --format_json
credmark-dev run finance.var-aave --input '{"window": "1000 days", "intervals": ["1 day"], "as_ofs": ["2022-02-15"], "as_of_is_range":true, "confidences": [0.01], "dev_mode":true, "verbose":true, "aave_history":false}' -l aave.token-asset,aave.lending-pool-assets,finance.var-engine,finance.var-reference,token.price-ext,finance.get-one,uniswap-v2.get-average-price,uniswap-v3.get-average-price,sushiswap.get-average-price -b 14234904 --format_json
credmark-dev run finance.var-aave --input '{"window": "365 days", "intervals": ["10 day"], "as_ofs": ["2020-11-30", "2021-02-15"], "as_of_is_range":true, "confidences": [0.01], "dev_mode":true, "verbose":true, "aave_history":false}' -l aave.token-asset,aave.lending-pool-assets,finance.var-engine,finance.var-reference,token.price-ext,finance.get-one,uniswap-v2.get-average-price,uniswap-v3.get-average-price,sushiswap.get-average-price -b 14234904 --format_json
credmark-dev run finance.var-aave --input '{"window": "365 days", "intervals": ["10 day"], "as_ofs": ["2020-11-30", "2021-01-31"], "as_of_is_range":true, "confidences": [0.01], "dev_mode":true, "verbose":true, "aave_history":false}' -l aave.token-asset,aave.lending-pool-assets,finance.var-engine,finance.var-reference,token.price-ext,finance.get-one,uniswap-v2.get-average-price,uniswap-v3.get-average-price,sushiswap.get-average-price -b 14234904 --format_json
credmark-dev run finance.var-aave --input '{"window": "365 days", "intervals": ["10 day"], "as_ofs": ["2021-01-31", "2021-03-01"], "as_of_is_range":true, "confidences": [0.01], "dev_mode":true, "verbose":true, "aave_history":false}' -l aave.token-asset,aave.lending-pool-assets,finance.var-engine,finance.var-reference,token.price-ext,finance.get-one,uniswap-v2.get-average-price,uniswap-v3.get-average-price,sushiswap.get-average-price -b 14234904 --format_json
credmark-dev run finance.var-aave --input '{"window": "365 days", "intervals": ["10 day"], "as_ofs": ["2021-03-01", "2021-05-31"], "as_of_is_range":true, "confidences": [0.01], "dev_mode":true, "verbose":true, "aave_history":false}' -l aave.token-asset,aave.lending-pool-assets,finance.var-engine,finance.var-reference,token.price-ext,finance.get-one,uniswap-v2.get-average-price,uniswap-v3.get-average-price,sushiswap.get-average-price -b 14234904 --format_json
credmark-dev run finance.var-aave --input '{"window": "365 days", "intervals": ["10 day"], "as_ofs": ["2021-05-31", "2021-06-30"], "as_of_is_range":true, "confidences": [0.01], "dev_mode":true, "verbose":true, "aave_history":false}' -l aave.token-asset,aave.lending-pool-assets,finance.var-engine,finance.var-reference,token.price-ext,finance.get-one,uniswap-v2.get-average-price,uniswap-v3.get-average-price,sushiswap.get-average-price -b 14234904 --format_json
credmark-dev run finance.var-aave --input '{"window": "365 days", "intervals": ["10 day"], "as_ofs": ["2021-06-30", "2021-08-31"], "as_of_is_range":true, "confidences": [0.01], "dev_mode":true, "verbose":true, "aave_history":false}' -l aave.token-asset,aave.lending-pool-assets,finance.var-engine,finance.var-reference,token.price-ext,finance.get-one,uniswap-v2.get-average-price,uniswap-v3.get-average-price,sushiswap.get-average-price -b 14234904 --format_json
credmark-dev run finance.var-aave --input '{"window": "365 days", "intervals": ["10 day"], "as_ofs": ["2021-08-31", "2021-10-30"], "as_of_is_range":true, "confidences": [0.01], "dev_mode":true, "verbose":true, "aave_history":false}' -l aave.token-asset,aave.lending-pool-assets,finance.var-engine,finance.var-reference,token.price-ext,finance.get-one,uniswap-v2.get-average-price,uniswap-v3.get-average-price,sushiswap.get-average-price -b 14234904 --format_json
credmark-dev run finance.var-aave --input '{"window": "365 days", "intervals": ["10 day"], "as_ofs": ["2021-10-30", "2021-12-31"], "as_of_is_range":true, "confidences": [0.01], "dev_mode":true, "verbose":true, "aave_history":false}' -l aave.token-asset,aave.lending-pool-assets,finance.var-engine,finance.var-reference,token.price-ext,finance.get-one,uniswap-v2.get-average-price,uniswap-v3.get-average-price,sushiswap.get-average-price -b 14234904 --format_json
credmark-dev run finance.var-aave --input '{"window": "365 days", "intervals": ["10 day"], "as_ofs": ["2021-12-31", "2022-02-20"], "as_of_is_range":true, "confidences": [0.01], "dev_mode":true, "verbose":true, "aave_history":false}' -l aave.token-asset,aave.lending-pool-assets,finance.var-engine,finance.var-reference,token.price-ext,finance.get-one,uniswap-v2.get-average-price,uniswap-v3.get-average-price,sushiswap.get-average-price -b 14234904 --format_json
